"""empty message

Revision ID: abedd60de62e
Revises: c4bd1667c4f6
Create Date: 2024-05-10 23:40:37.767104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abedd60de62e'
down_revision = 'c4bd1667c4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###
